# github action for nodejs test with pnpm RUN TEST
name: RUN TEST
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install ollama
      run: curl -fsSL https://ollama.com/install.sh | sh
    - name: Run ollama
      run: |
        ollama serve &
        ollama pull phi3:mini
    - uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v3 
      with:
            version: 8  # Optional: specify a pnpm version
    - name: Install dependencies
      run: pnpm install
    - name: Run tests
      run: pnpm test
