# github action for nodejs test with pnpm RUN TEST
name: RUN TEST
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: pnpm install
    - name: Run tests
      run: pnpm test
